version: '3.4'

services:
  helpdesk:
    image: helpdesk:1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]